### ISSUE TITLE
Circular dependency between nbconvert and notebook

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_nbconvert#4]
Nbconvert tries to import `jupyter_notebook` in order to include some CSS files from it:

```python
from jupyter_notebook import DEFAULT_STATIC_FILES_PATH
```

This is causing test failures because we don't declare jupyter_notebook as a dependency, so it's not installed for the tests. We could add it as a dependency, but then there's a circular dependency, which is a bit messy.

**Comment by minrk** [comment]
If nbconvert to html depends on CSS from the notebook, then that just is a circular dependency, and should be expressed as such. Otherwise, we can give nbconvert a copy of the CSS at sdist time, and only have the circular dependency when running from dev.
